version: '1.20'

services:
  web:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - dynamodb
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
